// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcGrmUK0zIhOdMLgdA6N_6-ZDdQoMMUXA',
    appId: '1:137460531797:web:f10959c77cc70df22ecadc',
    messagingSenderId: '137460531797',
    projectId: 'lite-d01fb',
    authDomain: 'lite-d01fb.firebaseapp.com',
    storageBucket: 'lite-d01fb.firebasestorage.app',
    measurementId: 'G-W2K63S7B7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19AortImGHk6-CcoWhB_8z8M38BZS7GA',
    appId: '1:137460531797:android:302d0c5e98fab4cb2ecadc',
    messagingSenderId: '137460531797',
    projectId: 'lite-d01fb',
    storageBucket: 'lite-d01fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPF1e8KLXcT8qeI9l-MHoEdFTHZV_tZmU',
    appId: '1:137460531797:ios:e0ef48b0c56122a12ecadc',
    messagingSenderId: '137460531797',
    projectId: 'lite-d01fb',
    storageBucket: 'lite-d01fb.firebasestorage.app',
    iosBundleId: 'com.example.youtubeLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPF1e8KLXcT8qeI9l-MHoEdFTHZV_tZmU',
    appId: '1:137460531797:ios:e0ef48b0c56122a12ecadc',
    messagingSenderId: '137460531797',
    projectId: 'lite-d01fb',
    storageBucket: 'lite-d01fb.firebasestorage.app',
    iosBundleId: 'com.example.youtubeLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcGrmUK0zIhOdMLgdA6N_6-ZDdQoMMUXA',
    appId: '1:137460531797:web:b702d14006bdc3022ecadc',
    messagingSenderId: '137460531797',
    projectId: 'lite-d01fb',
    authDomain: 'lite-d01fb.firebaseapp.com',
    storageBucket: 'lite-d01fb.firebasestorage.app',
    measurementId: 'G-CHQ5KPC40Y',
  );
}
